// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: creds.proto

package net.nyhm.driveup.proto;

/**
 * Protobuf enum {@code net.nyhm.driveup.proto.Access}
 */
public enum Access
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>READ = 0;</code>
   */
  READ(0),
  /**
   * <code>PATH = 1;</code>
   */
  PATH(1),
  /**
   * <code>FULL = 2;</code>
   */
  FULL(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>READ = 0;</code>
   */
  public static final int READ_VALUE = 0;
  /**
   * <code>PATH = 1;</code>
   */
  public static final int PATH_VALUE = 1;
  /**
   * <code>FULL = 2;</code>
   */
  public static final int FULL_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Access valueOf(int value) {
    return forNumber(value);
  }

  public static Access forNumber(int value) {
    switch (value) {
      case 0: return READ;
      case 1: return PATH;
      case 2: return FULL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Access>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Access> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Access>() {
          public Access findValueByNumber(int number) {
            return Access.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return net.nyhm.driveup.proto.Creds.getDescriptor().getEnumTypes().get(0);
  }

  private static final Access[] VALUES = values();

  public static Access valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Access(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:net.nyhm.driveup.proto.Access)
}

