// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: creds.proto

package net.nyhm.driveup.proto;

public final class Creds {
  private Creds() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_nyhm_driveup_proto_AppConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_nyhm_driveup_proto_AppConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_nyhm_driveup_proto_AppConfig_CredsStoreEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_nyhm_driveup_proto_AppConfig_CredsStoreEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_nyhm_driveup_proto_CredsData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_nyhm_driveup_proto_CredsData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_nyhm_driveup_proto_CredsData_EntriesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_nyhm_driveup_proto_CredsData_EntriesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_net_nyhm_driveup_proto_GpgData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_net_nyhm_driveup_proto_GpgData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013creds.proto\022\026net.nyhm.driveup.proto\"\227\002" +
      "\n\tAppConfig\022\017\n\007version\030\001 \001(\005\022\020\n\010app_name" +
      "\030\002 \001(\t\022\026\n\016client_secrets\030\003 \001(\t\022F\n\013creds_" +
      "store\030\004 \003(\01321.net.nyhm.driveup.proto.App" +
      "Config.CredsStoreEntry\0221\n\010gpg_data\030\005 \001(\013" +
      "2\037.net.nyhm.driveup.proto.GpgData\032T\n\017Cre" +
      "dsStoreEntry\022\013\n\003key\030\001 \001(\t\0220\n\005value\030\002 \001(\013" +
      "2!.net.nyhm.driveup.proto.CredsData:\0028\001\"" +
      "|\n\tCredsData\022?\n\007entries\030\001 \003(\0132..net.nyhm" +
      ".driveup.proto.CredsData.EntriesEntry\032.\n" +
      "\014EntriesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\014:\0028\001\"/\n\007GpgData\022\021\n\trecipient\030\001 \001(\t\022\021\n\tp" +
      "ublicKey\030\002 \001(\014B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_net_nyhm_driveup_proto_AppConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_net_nyhm_driveup_proto_AppConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_nyhm_driveup_proto_AppConfig_descriptor,
        new java.lang.String[] { "Version", "AppName", "ClientSecrets", "CredsStore", "GpgData", });
    internal_static_net_nyhm_driveup_proto_AppConfig_CredsStoreEntry_descriptor =
      internal_static_net_nyhm_driveup_proto_AppConfig_descriptor.getNestedTypes().get(0);
    internal_static_net_nyhm_driveup_proto_AppConfig_CredsStoreEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_nyhm_driveup_proto_AppConfig_CredsStoreEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_net_nyhm_driveup_proto_CredsData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_net_nyhm_driveup_proto_CredsData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_nyhm_driveup_proto_CredsData_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_net_nyhm_driveup_proto_CredsData_EntriesEntry_descriptor =
      internal_static_net_nyhm_driveup_proto_CredsData_descriptor.getNestedTypes().get(0);
    internal_static_net_nyhm_driveup_proto_CredsData_EntriesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_nyhm_driveup_proto_CredsData_EntriesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_net_nyhm_driveup_proto_GpgData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_net_nyhm_driveup_proto_GpgData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_net_nyhm_driveup_proto_GpgData_descriptor,
        new java.lang.String[] { "Recipient", "PublicKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
