// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: creds.proto

package net.nyhm.driveup.proto;

public interface CredsDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.nyhm.driveup.proto.CredsData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, bytes&gt; entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>map&lt;string, bytes&gt; entries = 1;</code>
   */
  boolean containsEntries(
      java.lang.String key);
  /**
   * Use {@link #getEntriesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getEntries();
  /**
   * <code>map&lt;string, bytes&gt; entries = 1;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getEntriesMap();
  /**
   * <code>map&lt;string, bytes&gt; entries = 1;</code>
   */

  com.google.protobuf.ByteString getEntriesOrDefault(
      java.lang.String key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; entries = 1;</code>
   */

  com.google.protobuf.ByteString getEntriesOrThrow(
      java.lang.String key);
}
