// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: creds.proto

package net.nyhm.driveup.proto;

public interface GpgDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:net.nyhm.driveup.proto.GpgData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recipient = 1;</code>
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecipientBytes();

  /**
   * <code>bytes publicKey = 2;</code>
   */
  com.google.protobuf.ByteString getPublicKey();
}
